// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Stashboard.Api.Data;

#nullable disable

namespace Stashboard.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522143000_EncryptTelegramBotToken")]
    partial class EncryptTelegramBotToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");
#pragma warning restore 612, 618
        }
    }
}
