// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stashboard.Api.Data;

#nullable disable

namespace Stashboard.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608130042_AddProxmoxDestroy")]
    partial class AddProxmoxDestroy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Stashboard.Api.Data.ContainerExecSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContainerExecSettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.EmailSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppBaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseStartTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.HealthCheckSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HealthCheckSettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.HostShellSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HostShellSettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.ImagePruneSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImagePruneSettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.ProxmoxConsoleSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxmoxConsoleSettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.ProxmoxDestroySettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxmoxDestroySettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.ProxmoxUpdateApplySettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProxmoxUpdateApplySettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevokedReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Stashboard.Api.Data.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DashboardGroupByCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DashboardSortMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedAccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PendingEmailTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingEmailTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramBotTokenEncrypted")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WebResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebResourceId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowExec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowHostShell")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowImagePrune")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComposeProjectPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HostType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastImagePruneUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PruneUnusedImages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshHost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SshPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshPrivateKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshPrivateKeyPassphraseEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshRemoteSocketPath")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SshUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsCaCertEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsClientCertEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsClientKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("DockerConnections");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerExecSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesFromClient")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesToClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DockerConnectionId", "StartedUtc");

                    b.HasIndex("InitiatedByUserId", "StartedUtc");

                    b.ToTable("DockerExecSessions");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerPruneRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImagesDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludedUnused")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SpaceReclaimedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("DockerConnectionId", "StartedUtc");

                    b.ToTable("DockerPruneRuns");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerUpdateAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComposeProject")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerWatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HealthVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HealthVerifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WebResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentAttemptId");

                    b.HasIndex("WebResourceId");

                    b.HasIndex("DockerConnectionId", "CompletedUtc");

                    b.HasIndex("DockerWatchId", "CompletedUtc");

                    b.ToTable("DockerUpdateAttempts");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerWatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsAccessKeyIdEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsRegion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsSecretAccessKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("CheckAtTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckEveryHours")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckOnDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentVersionTag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubPatEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNotificationSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNotifiedDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTelegramNotifiedDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdateDetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastWebhookReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestReleaseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestReleaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVersionTag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistryAuthType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistryHost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryPasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryUsernameEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagPatternFilter")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdateStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WebResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookToken")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DockerConnectionId");

                    b.HasIndex("WebResourceId");

                    b.HasIndex("WebhookToken")
                        .IsUnique();

                    b.HasIndex("DockerConnectionId", "ContainerName")
                        .IsUnique();

                    b.HasIndex("UserId", "Enabled", "LastCheckedUtc");

                    b.ToTable("DockerWatches");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.HostShellSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesFromClient")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesToClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshHost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SshUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DockerConnectionId", "StartedUtc");

                    b.HasIndex("InitiatedByUserId", "StartedUtc");

                    b.ToTable("HostShellSessions");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowConsole")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowDestroy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiTokenId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiTokenSecretEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("CheckAtTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckEveryHours")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckOnDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNotificationSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNotifiedSignature")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTelegramNotifiedSignature")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastWebhookReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServerType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkipTlsVerify")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshHost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SshPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshPrivateKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshPrivateKeyPassphraseEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TelemetryPollSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookToken")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebhookToken")
                        .IsUnique();

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.HasIndex("UserId", "Enabled", "LastCheckedUtc");

                    b.ToTable("ProxmoxConnections");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxConsoleSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesFromClient")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesToClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProxmoxConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByUserId", "StartedUtc");

                    b.HasIndex("ProxmoxConnectionId", "StartedUtc");

                    b.ToTable("ProxmoxConsoleSessions");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxDestroyAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DestroyedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProxmoxConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByUserId", "DestroyedUtc");

                    b.HasIndex("ProxmoxConnectionId", "DestroyedUtc");

                    b.ToTable("ProxmoxDestroyAudits");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxGuestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DiskBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MemoryBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MonitoringEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("MonitoringSnoozedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PendingUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProxmoxConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UptimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProxmoxConnectionId", "VmId")
                        .IsUnique();

                    b.ToTable("ProxmoxGuests");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxMonitoringAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Bulk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MonitoringEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProxmoxConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByUserId", "ChangedUtc");

                    b.HasIndex("ProxmoxConnectionId", "ChangedUtc");

                    b.ToTable("ProxmoxMonitoringAudits");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxNodeAlertSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryMask")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CpuCrit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CpuWarn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastNotificationSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNotifiedSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTelegramNotifiedSignature")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MemCrit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MemWarn")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProxmoxConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StorageCrit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StorageWarn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TempCrit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TempWarn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProxmoxConnectionId")
                        .IsUnique();

                    b.ToTable("ProxmoxNodeAlertSettings");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxNodeAlertStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metric")
                        .HasColumnType("TEXT");

                    b.Property<long?>("NicCounterBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingLevel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProxmoxConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Threshold")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProxmoxConnectionId", "Category")
                        .IsUnique();

                    b.ToTable("ProxmoxNodeAlertStates");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxUpdateSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesToClient")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProxmoxConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VmId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByUserId", "StartedUtc");

                    b.HasIndex("ProxmoxConnectionId", "StartedUtc");

                    b.ToTable("ProxmoxUpdateSessions");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("AdditionalUrlConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdditionalUrlHealthCheckEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalUrlLastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdditionalUrlLastResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdditionalUrlStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomLogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedStatusRange")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthCheckMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthCheckUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogoSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MainUrlConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MainUrlHealthCheckEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OfflineNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DockerConnectionId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("WebResources");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceTagEntity", b =>
                {
                    b.Property<Guid>("WebResourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("WebResourceId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("WebResourceTags");
                });

            modelBuilder.Entity("Stashboard.Api.Data.RefreshTokenEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CategoryEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CredentialEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.WebResourceEntity", "WebResource")
                        .WithMany("Credentials")
                        .HasForeignKey("WebResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebResource");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerConnectionEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerExecSessionEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerPruneRunEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerUpdateAttemptEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Core.Entities.DockerWatchEntity", null)
                        .WithMany()
                        .HasForeignKey("DockerWatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stashboard.Core.Entities.DockerUpdateAttemptEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentAttemptId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stashboard.Core.Entities.WebResourceEntity", null)
                        .WithMany()
                        .HasForeignKey("WebResourceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerWatchEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", "DockerConnection")
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Core.Entities.WebResourceEntity", "WebResource")
                        .WithMany("DockerWatches")
                        .HasForeignKey("WebResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DockerConnection");

                    b.Navigation("WebResource");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.HostShellSessionEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxConnectionEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxConsoleSessionEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Core.Entities.ProxmoxConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("ProxmoxConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxDestroyAuditEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Core.Entities.ProxmoxConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("ProxmoxConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxGuestEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.ProxmoxConnectionEntity", "ProxmoxConnection")
                        .WithMany()
                        .HasForeignKey("ProxmoxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProxmoxConnection");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxMonitoringAuditEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Core.Entities.ProxmoxConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("ProxmoxConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxNodeAlertSettingsEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.ProxmoxConnectionEntity", "ProxmoxConnection")
                        .WithMany()
                        .HasForeignKey("ProxmoxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProxmoxConnection");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxNodeAlertStateEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.ProxmoxConnectionEntity", "ProxmoxConnection")
                        .WithMany()
                        .HasForeignKey("ProxmoxConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProxmoxConnection");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.ProxmoxUpdateSessionEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Core.Entities.ProxmoxConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("ProxmoxConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Stashboard.Core.Entities.TagEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.CategoryEntity", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", "DockerConnection")
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DockerConnection");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceTagEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.TagEntity", "Tag")
                        .WithMany("WebResourceTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Core.Entities.WebResourceEntity", "Service")
                        .WithMany("WebResourceTags")
                        .HasForeignKey("WebResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Stashboard.Api.Data.UserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.TagEntity", b =>
                {
                    b.Navigation("WebResourceTags");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceEntity", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("DockerWatches");

                    b.Navigation("WebResourceTags");
                });
#pragma warning restore 612, 618
        }
    }
}
