// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stashboard.Api.Data;

#nullable disable

namespace Stashboard.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522113017_AddEmailSettings")]
    partial class AddEmailSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Stashboard.Api.Data.EmailSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppBaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseStartTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("Stashboard.Api.Data.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RevokedReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Stashboard.Api.Data.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DashboardGroupByCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DashboardSortMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailedAccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PendingEmailTokenExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingEmailTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramBotToken")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WebResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebResourceId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HostType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SshHost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SshPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SshPrivateKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshPrivateKeyPassphraseEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("SshRemoteSocketPath")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SshUsername")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsCaCertEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsClientCertEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("TlsClientKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("DockerConnections");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerUpdateAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerWatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HealthVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HealthVerifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("WebResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WebResourceId");

                    b.HasIndex("DockerConnectionId", "CompletedUtc");

                    b.HasIndex("DockerWatchId", "CompletedUtc");

                    b.ToTable("DockerUpdateAttempts");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerWatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsAccessKeyIdEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsRegion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AwsSecretAccessKeyEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("CheckAtTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("CheckEveryHours")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckOnDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentVersionTag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubPatEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNotificationSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNotifiedDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTelegramNotifiedDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdateDetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastWebhookReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestDigest")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestReleaseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestReleaseUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVersionTag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("RegistryAuthType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistryHost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryPasswordEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistryUsernameEncrypted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagPatternFilter")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpdateNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpdateStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WebResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookToken")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DockerConnectionId");

                    b.HasIndex("WebResourceId");

                    b.HasIndex("WebhookToken")
                        .IsUnique();

                    b.HasIndex("DockerConnectionId", "ContainerName")
                        .IsUnique();

                    b.HasIndex("UserId", "Enabled", "LastCheckedUtc");

                    b.ToTable("DockerWatches");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdditionalUrlHealthCheckEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalUrlLastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdditionalUrlLastResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdditionalUrlStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomLogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DockerConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedStatusRange")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthCheckMethod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HealthCheckUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogoSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MainUrlHealthCheckEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OfflineNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DockerConnectionId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("WebResources");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceTagEntity", b =>
                {
                    b.Property<Guid>("WebResourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("WebResourceId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("WebResourceTags");
                });

            modelBuilder.Entity("Stashboard.Api.Data.RefreshTokenEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CategoryEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CredentialEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.WebResourceEntity", "WebResource")
                        .WithMany("Credentials")
                        .HasForeignKey("WebResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebResource");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerConnectionEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerUpdateAttemptEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", null)
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Core.Entities.DockerWatchEntity", null)
                        .WithMany()
                        .HasForeignKey("DockerWatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stashboard.Core.Entities.WebResourceEntity", null)
                        .WithMany()
                        .HasForeignKey("WebResourceId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Stashboard.Core.Entities.DockerWatchEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", "DockerConnection")
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Core.Entities.WebResourceEntity", "WebResource")
                        .WithMany("DockerWatches")
                        .HasForeignKey("WebResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DockerConnection");

                    b.Navigation("WebResource");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.TagEntity", b =>
                {
                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.CategoryEntity", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Core.Entities.DockerConnectionEntity", "DockerConnection")
                        .WithMany()
                        .HasForeignKey("DockerConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Stashboard.Api.Data.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DockerConnection");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceTagEntity", b =>
                {
                    b.HasOne("Stashboard.Core.Entities.TagEntity", "Tag")
                        .WithMany("WebResourceTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stashboard.Core.Entities.WebResourceEntity", "Service")
                        .WithMany("WebResourceTags")
                        .HasForeignKey("WebResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Stashboard.Api.Data.UserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.TagEntity", b =>
                {
                    b.Navigation("WebResourceTags");
                });

            modelBuilder.Entity("Stashboard.Core.Entities.WebResourceEntity", b =>
                {
                    b.Navigation("Credentials");

                    b.Navigation("DockerWatches");

                    b.Navigation("WebResourceTags");
                });
#pragma warning restore 612, 618
        }
    }
}
